title: 我的忍者之路-原型与面向对象2
date: 2016-03-14 22:48:10
tags: [JavaScript, 提升]
---

## 疑难陷阱
常言道生活处处是陷阱，作为一名忍者，怎能落入陷阱呢？JavaScript中原型、实例化以及继承相关的陷阱，我们就要小心翼翼地迈过去！ 

### 扩展对象
一个极其严重的错误就是去扩展原生 Object.prototype。因为在扩展该原型时，所有的对象都会接收这些额外的属性。在遍历对象属性的时候，就会出现意想不到的行为：
``` javascript
Object.prototype.keys = function() {
  var keys = [];
  for (var p in this) keys.push(p);
  return keys;
}

var obj = {a: 1, b: 2, c: 3};
assert(obj.keys().length == 3, 'There are three properties in this object');
assert(obj.keys().length == 4, 'There are four');

//\\There are three properties in this object
//There are four
```
给 Object 添加一个 keys() 方法，该方法返回一个包括所有属性名称的数组。但结果并不如人意，问题肯定是出在了给 Object 添加的 keys() 方法上。
>我们给所有对象添加了一个属性，并且会出现在计数中，迫使所有代码必须考虑到这个额外的属性，很显然是不可接受的。

JavaScript 提供了一个名为 hasOwnProperty() 的方法，他可以确定一个属性是在对象实例上定义的：
``` javascript
Object.prototype.kes = function() {
  var keys = [];
  for (var p in this) {
    if (this.hasOwnProperty(p)) keys.push(p);
  }
  return keys;
}

var obj2 = {a: 1, b: 2, c: 3};
assert(obj2.kes().length == 3, 'There are three properties in this object');

//There are three properties in this object
```
>虽然它能解决这个问题，但是我们还是不能滥用。一般我们应该使用这种解决方法 _保护_ 自己的代码免受影响，而不是期望其他人必须要保护自己的代码免受我们(不好)的代码的影响。

### 扩展数字
除了 Object ，其他原生对象的原型进行扩展相对来说比较安全，但是还有一个挑刺的 Number：
``` javascript
Number.prototype.add = function(num) {
  return this + num;
}

var n = 5;
assert(n.add(3) == 8, 'It works when the number is in a variable.');
assert((5).add(3) == 8, 'Also works if a number is wrapped in parentheses.');
assert(5.add(3) == 8, 'What about a simple literal?');

console => Uncaught SyntaxError: Unexpected token ILLEGAL  demo.js:8
```
我们在 Number 上定义一个新方法 add()，它将参数与自身数值进行相加，然后返回。我们用各种方式验证该方法：

* 用数字变量验证
* 用数字表达式
* 直接用数字字面量

结果出乎意料，控制台报错，语法解析器不能处理字面量这种情况。虽然其背后的逻辑相当模糊，但是我们如果这样写：
``` javascript
assert(5..add(3) == 8, 'It\'s done');

// It's done
```
5.. 很奇怪的写法（多了一个点），但是他实际上是有迹可循的。如果我们把 5. 可以看成 (5)，这就一目了然了。

>总之我们最好避免在 Number 的原型上做扩展。

### 子类化原生对象
原生对象的子类化，例如我们对 Array 进行子类化的时候，一切似乎都如预期那样：
``` javascript
function MyArray() {}

MyArray.prototype = new Array();

var mine = new MyArray();
mine.push(1, 2, 3);

assert(mine.length == 3, 'All the items are in our sub-classed array.');
assert(mine instanceof Array, 'Verify that we implement Array functionality.');

//All the items are in our sub-classed array. \\ IE7
//Verify that we implement Array functionality.
```
没出错，不对！打开 IE （亲测IE7不行）试试，果不其然，他有不同的表现。length 属性相当特殊，密切关系到 Array 的数字指标，但 IE 的实现却不好。这种情况下，更好的策略是 _单独实现原生对象的各个功能，而不是扩展出子类_：
``` javascript
function YourArray() {}
YourArray.prototype.length = 0;     //#1

(function() {
  var methods = ['push', 'pop', 'shift', 'unshift', 'slice', 'splice', 'join'];
  for (var i = 0, j = methods.length; i < j; i++) (function(name) {
    YourArray.prototype[name] = function() {
      return Array.prototype[name].apply(this, arguments);
    }
  })(methods[i]);
})()

var your = new YourArray();
your.push(1, 2, 3);

assert(your.length == 3, 'All the items are in our sub-classed array.');
assert(!(your instanceof Array), "We aren't subclassing Array, though.");


//All the items are in our sub-classed array.
//We aren't subclassing Array, though.

//#1 唯一需要自己实现的是 length 属性，因为 IE ！。
```

### 实例化问题
我们知道，函数的两种用途：

* 作为“普通”的函数
* 作为构造器

正因为如此，可能有时并不清楚在代码中的到底是哪个：
``` javascript
function User(first, last) {
  this.name = first + ' ' + last;
}

var user = User('Ichigo', 'Kurosaki');

assert(user, 'User instantiated');                                       //1.
assert(user.name == 'Ichigo Kurosaki', 'User name correctly assigned');  //2.


//\\User instantiated
console => Uncaught TypeError: Cannot read property 'name' of undefined  demo.js:8
```
* (1.)对象没有被实例化
* (2.)所以抛出错误  

除了意想不到的错误，构造器函数作为普通函数进行调用，会产生微妙的副作用，如污染当前作用域（通常是全局命名空间）：
``` javascript
function Player(first, last) {
  this.pname = first + ' ' + last;
}

var pname = 'Rukia';

var player = Player('Ichigo', 'Kurosaki');
assert(pname == 'Rukia', 'Name was set to Rukia.');

//\\Name was set to Rukia.
```
>函数作为构造器调用时，函数调用上下文是新分配的对象，但作为普通函数调用时，其上下文是全局作用域。

作为忍者，我们可否判断一个函数到底是如何进行调用的：
``` javascript
function Test() {
  return this instanceof arguments.callee;
}

assert(!Test(), "We didn't instantiate, so it returns false.");
assert(new Test(), 'We did instantiate, returning true.');

//We didn't instantiate, so it returns false.
//We did instantiate, returning true.
```
回顾一些重要的概念：

* 通过 arguments.callee 可以得到当前执行函数的引用
* “普通”函数的上下文是全局作用域（除非强制修改）
* 利用 instanceof 操作符测试已构建对象是否构建于指定的构造器

>this instanceof arguments.callee 作为构造器时 true，作为普通函数时 false。

懂得如何判断了，在错误调用时我们可否来主动地纠正他：
``` javascript
function Client(first, last) {
  if (!(this instanceof arguments.callee)) {
    return new Client(first, last);
  }
  this.cname = first + ' ' + last;
}
var cname = 'Rukia';

var client = Client('Ichigo', 'Kurosaki');

assert(cname == 'Rukia', 'Cname was set to Rukia.');
assert(client instanceof Client, 'Client instantiated');
assert(client.cname == 'Ichigo Kurosaki', 'Client cname correctly assigned');

//Cname was set to Rukia.
//Client instantiated
//Client cname correctly assigned
```
仿佛很美丽，但是我们需要 _思考_ ：

* callee 不支持严格模式
* 这个纠正是否是用户所需要的呢 

所以有巧妙的解决方法并不总是意味着我们就应该用他。换言之，我们习得一身武功，并不需要时时刻刻展示出来。作为忍者，该出手时才出手！

